[tool.pytest.ini_options]
log_file = "/home/ubuntuuser/karra/securities_load/securities_load.log"
log_file_level = "DEBUG"
log_file_format = "%(asctime)s %(levelname)s %(message)s"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
